blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/UtkarshUmre/StoreMy/discussions
    about: Use GitHub Discussions for questions and general discussion about StoreMy.
